from contextlib import AbstractContextManager
from io import StringIO

IS_WIN32 = ...

class ProcInfo:
    def __init__(self, pid, uid, stat, args) -> None: ...

def captured_stdout(stdin: str = "") -> AbstractContextManager[StringIO]: ...

class StaticProperty:
    def __init__(self, function) -> None: ...
    def __get__(self, obj, klass=...): ...

def getdoc(obj) -> str | None: ...
def read_fd_decode_safely(fd, size: int = 4096) -> tuple[bytes, str]: ...
